### ISSUE TITLE
tests hang on Windows

### ISSUE THREAD

**Issue by chorny** [shoichikaji/Process-Pipeline#1]
01_basic.t:

```
    # Subtest: fail
    ok 1
    # Can't exec "oooops": No such file or directory at C:\strawberry160\cpan\build\Process-Pipeline-0.01-n2H1SR\blib\lib/Process/Pipeline.pm line 173.
    1..1
ok 1 - fail
(hangs)
```

**Comment by skaji** [comment]
Thank you for your reporting.
This module uses *nix specific features, so I disabled Windows installation in https://github.com/skaji/Process-Pipeline/commit/d3fed9e2ce4cedf40d31fb2e0071a3bfe8296f48.
