### ISSUE TITLE
Tests may fail (on slower systems?)

### ISSUE THREAD

**Issue by eserte** [shoichikaji/Process-Pipeline#2]
On my smokers I observe occasional test failures like these:
- http://www.cpantesters.org/cpan/report/77b110e4-ee8e-11e5-ba27-9cc9fcd2507e
- http://www.cpantesters.org/cpan/report/8cb35b2c-ee76-11e5-ac60-ae63fcd2507e

My impression is that this failure happens more often on slower systems, and more often on freebsd than linux systems.

I guess that the problem is caused by `select undef, undef, undef, 0.01` in `Process::Pipeline::Result::start`. The value feels arbitrary to me, and in fact, if I lower the sleep value, then it starts to fail on all systems; on the other hand, if I increase this value, then it starts to pass on all systems.

Is it possible to get rid of this `select()` somehow?

**Comment by skaji** [comment]
Thank you for your reporting.
Removed select() in https://metacpan.org/release/SKAJI/Process-Pipeline-0.03

**Comment by eserte** [comment]
Looks good now: http://fast-matrix.cpantesters.org/?dist=Process-Pipeline%200.03
