### ISSUE TITLE
Pod: $result → $r

### ISSUE THREAD

**Issue by eserte** [shoichikaji/Process-Pipeline#3]
In the following Pod lines `$result` should be `$r`:
- https://metacpan.org/source/SKAJI/Process-Pipeline-0.02/lib/Process/Pipeline.pm#L219
- https://metacpan.org/source/SKAJI/Process-Pipeline-0.02/lib/Process/Pipeline.pm#L233

**Comment by skaji** [comment]
Thank you for your reporting.
Use $result in https://metacpan.org/release/SKAJI/Process-Pipeline-0.03
